create schema Educalife;
create table Educalife.banco (id varchar(32) not null, codigo varchar(255), febraban boolean, nome varchar(255) not null, website varchar(255), primary key (id));
create table Educalife.calendario_atividade (id varchar(32) not null, dataFim date, dataInicio date not null, descricao varchar(255) not null, primary key (id));
create table Educalife.cargo (id varchar(32) not null, ativo boolean, codigo_cbo varchar(255) not null, denominacao varchar(255) not null, primary key (id));
create table Educalife.colaborador (id varchar(32) not null, data_admissao date, data_desligamento date, matricula varchar(255) not null, id_cargo varchar(32) not null, id_departamento varchar(32) not null, id_pessoa_fisica varchar(32) not null, primary key (id));
create table Educalife.conta_banco (id varchar(32) not null, agencia varchar(255) not null, numeroConta varchar(255) not null, operacao varchar(255), id_banco varchar(32) not null, id_pessoa_fisica varchar(32), primary key (id));
create table Educalife.curso (id varchar(32) not null, carga_horaria int4, descricao_curso text, nome_curso varchar(255) not null, status_curso varchar(255) not null, id_coordenador varchar(32) not null, primary key (id));
create table Educalife.deficiencia (id varchar(32) not null, descricao varchar(255), primary key (id));
create table Educalife.departamento (id varchar(32) not null, nome_departamento varchar(255) not null, id_unidade varchar(32) not null, primary key (id));
create table Educalife.empresa (id varchar(32) not null, contrato_social text, id_pessoa_juridica varchar(32), primary key (id));
create table Educalife.escolaridade (id varchar(32) not null, descricao varchar(255), primary key (id));
create table Educalife.estado_civil (id varchar(32) not null, descricao varchar(255), primary key (id));
create table Educalife.etnia (id varchar(32) not null, descricao varchar(255), primary key (id));
create table Educalife.genero (id varchar(32) not null, descricao varchar(255), primary key (id));
create table Educalife.IMAGES (ID varchar(255) not null, GALLERY varchar(255), IMAGE bytea, primary key (ID));
create table Educalife.localidade (id varchar(32) not null, ativo boolean, codigo varchar(255) not null, descricao varchar(255) not null, observacao varchar(255), id_unidade varchar(32) not null, primary key (id));
create table Educalife.OXDISCUSSIONCOMMENTS (id varchar(32) not null, comment text, discussionId varchar(32), time timestamp, userName varchar(30), primary key (id));
create table Educalife.pais (id varchar(32) not null, codigo varchar(255) not null, denominacao varchar(255) not null, primary key (id));
create table Educalife.papel_usuario (id varchar(32) not null, descricao varchar(255) not null, nome varchar(255) not null, primary key (id));
create table Educalife.pessoa_fisica (id varchar(32) not null, cpf varchar(255) not null, data_nascimento date not null, bairro varchar(255) not null, cep varchar(255) not null, cidade varchar(255) not null, complemento varchar(255), logradouro varchar(255) not null, numero varchar(255) not null, uf varchar(255) not null, foto bytea, naturalidade varchar(255), nome varchar(255) not null, nome_mae varchar(255), nome_pai varchar(255), tipo_sanguineo varchar(255), id_deficiencia varchar(32), id_tipo_logradouro varchar(32) not null, id_escolaridade varchar(32), id_estado_civil varchar(32), id_etnia varchar(32), id_genero varchar(32), id_nacionalidade varchar(32), primary key (id));
create table Educalife.pessoa_fisica_anotacoes (pessoa_fisica_id varchar(32) not null, anotacao text);
create table Educalife.pessoa_fisica_contatos (pessoa_fisica_id varchar(32) not null, descricao varchar(255), observacao varchar(255), tipo_contato varchar(255));
create table Educalife.pessoa_fisica_documentosIdentidade (pessoa_fisica_id varchar(32) not null, complemento varchar(255), data_expedicao date, numero varchar(255), orgao_expedidor varchar(255), tipo_identidade varchar(255));
create table Educalife.pessoa_juridica (id varchar(32) not null, cnpj varchar(255) not null, data_criacao date not null, bairro varchar(255) not null, cep varchar(255) not null, cidade varchar(255) not null, complemento varchar(255), logradouro varchar(255) not null, numero varchar(255) not null, uf varchar(255) not null, nome_fantasia varchar(255) not null, razao_social varchar(255) not null, id_tipo_logradouro varchar(32) not null, primary key (id));
create table Educalife.pessoa_juridica_contatos (pessoa_juridica_id varchar(32) not null, descricao varchar(255), observacao varchar(255), tipo_contato varchar(255));
create table Educalife.tipo_logradouro (id varchar(32) not null, codigo varchar(255) not null, descricao varchar(255) not null, primary key (id));
create table Educalife.turma (id varchar(32) not null, data_fim date not null, data_fim_inscricao date not null, data_inicio date not null, data_inicio_inscricao date not null, modalidade_turma varchar(255) not null, nome_turma varchar(255) not null, status_turma varchar(255) not null, id_curso varchar(32) not null, id_localidade varchar(32), primary key (id));
create table Educalife.turma_equipe (turma_id varchar(32) not null, funcao_equipe varchar(255), ministra_aula boolean, id_pessoa_fisica varchar(32));
create table Educalife.turma_ofertaVagas (turma_id varchar(32) not null, numero_vaga int4, publico_alvo varchar(255));
create table Educalife.unidade (id varchar(32) not null, bairro varchar(255) not null, cep varchar(255) not null, cidade varchar(255) not null, complemento varchar(255), logradouro varchar(255) not null, numero varchar(255) not null, uf varchar(255) not null, horario_funcionamento varchar(255), nome_unidade varchar(255) not null, id_empresa varchar(32) not null, id_tipo_logradouro varchar(32) not null, primary key (id));
create table Educalife.unidade_contatos (unidade_id varchar(32) not null, descricao varchar(255), observacao varchar(255), tipo_contato varchar(255));
create table Educalife.usuario (id varchar(32) not null, ativo boolean not null, login varchar(255) not null, senha varchar(64) not null, primary key (id));
create table Educalife.usuario_permissao (usuario_id varchar(32) not null, id_papel_usuario varchar(32));
alter table if exists Educalife.empresa drop constraint if exists UK_iga8xmsx8pc55q99qn3o8ivy6;
alter table if exists Educalife.empresa add constraint UK_iga8xmsx8pc55q99qn3o8ivy6 unique (id_pessoa_juridica);
create index IDXbhlx4vunn24ym1tbrlgq8g30m on Educalife.OXDISCUSSIONCOMMENTS (discussionId);
alter table if exists Educalife.colaborador add constraint FKiv1q5t84ba004n31x7ruwf5rg foreign key (id_cargo) references Educalife.cargo;
alter table if exists Educalife.colaborador add constraint FK7be8k2g6cixaflue3kmxkr5o4 foreign key (id_departamento) references Educalife.departamento;
alter table if exists Educalife.colaborador add constraint FKnkse4mppg0fexkwc6gy1cd3kn foreign key (id_pessoa_fisica) references Educalife.pessoa_fisica;
alter table if exists Educalife.conta_banco add constraint FKjr8pnin2x62ex3yucymtgrksf foreign key (id_banco) references Educalife.banco;
alter table if exists Educalife.conta_banco add constraint FKrmhpbawwhweh09fy7wrjf7otu foreign key (id_pessoa_fisica) references Educalife.pessoa_fisica;
alter table if exists Educalife.curso add constraint FKl3w67buyhwlfegsdg9t3jk73v foreign key (id_coordenador) references Educalife.colaborador;
alter table if exists Educalife.departamento add constraint FKdkg1is30jd8t548g90uh7jjfi foreign key (id_unidade) references Educalife.unidade;
alter table if exists Educalife.empresa add constraint FK79yt1i65lksuwnk98m95w8big foreign key (id_pessoa_juridica) references Educalife.pessoa_juridica;
alter table if exists Educalife.localidade add constraint FKa9ab9fayf9mvahwywrxkavpqx foreign key (id_unidade) references Educalife.unidade;
alter table if exists Educalife.pessoa_fisica add constraint FKeramm5vb4ge7yed5ui51k31k6 foreign key (id_deficiencia) references Educalife.deficiencia;
alter table if exists Educalife.pessoa_fisica add constraint FKh168he306g5c7elhgavoq7akm foreign key (id_tipo_logradouro) references Educalife.tipo_logradouro;
alter table if exists Educalife.pessoa_fisica add constraint FK3y4pqme027ka6ee2kcqoaxbqi foreign key (id_escolaridade) references Educalife.escolaridade;
alter table if exists Educalife.pessoa_fisica add constraint FKqjo77k9knjsduakttdy75ue26 foreign key (id_estado_civil) references Educalife.estado_civil;
alter table if exists Educalife.pessoa_fisica add constraint FKs11jdtw0apcey0tf011yhvgf foreign key (id_etnia) references Educalife.etnia;
alter table if exists Educalife.pessoa_fisica add constraint FKc8bqmx49pw09qkc2u2n8gd2fr foreign key (id_genero) references Educalife.genero;
alter table if exists Educalife.pessoa_fisica add constraint FKftlo8bcaufh3hx4kxqyc263ld foreign key (id_nacionalidade) references Educalife.pais;
alter table if exists Educalife.pessoa_fisica_anotacoes add constraint FKih4xh24cn98fnq6w3ui4kcloo foreign key (pessoa_fisica_id) references Educalife.pessoa_fisica;
alter table if exists Educalife.pessoa_fisica_contatos add constraint FKbv907ahir4ypgtw87r1gqqpov foreign key (pessoa_fisica_id) references Educalife.pessoa_fisica;
alter table if exists Educalife.pessoa_fisica_documentosIdentidade add constraint FK5bx6rdhpme72fb0bv1omhmjrl foreign key (pessoa_fisica_id) references Educalife.pessoa_fisica;
alter table if exists Educalife.pessoa_juridica add constraint FKma10cu9eg6i0rqcjufcow4s95 foreign key (id_tipo_logradouro) references Educalife.tipo_logradouro;
alter table if exists Educalife.pessoa_juridica_contatos add constraint FKftldluw92br9dp06yw2tw9ltl foreign key (pessoa_juridica_id) references Educalife.pessoa_juridica;
alter table if exists Educalife.turma add constraint FKqksqho9nu4sweas62bmdjibqd foreign key (id_curso) references Educalife.curso;
alter table if exists Educalife.turma add constraint FKl4e1x39p7he0u577pd8dme35u foreign key (id_localidade) references Educalife.localidade;
alter table if exists Educalife.turma_equipe add constraint FKgh7mkjnr0kxp8h6f1p91vg7gs foreign key (id_pessoa_fisica) references Educalife.pessoa_fisica;
alter table if exists Educalife.turma_equipe add constraint FKl4lv1h0hlfv5f4wbro7ds6hdv foreign key (turma_id) references Educalife.turma;
alter table if exists Educalife.turma_ofertaVagas add constraint FK9rggyrduwgtp0vd3g8gsmtv8 foreign key (turma_id) references Educalife.turma;
alter table if exists Educalife.unidade add constraint FKcbfaqsmvke1dh6ua8fusi1gc9 foreign key (id_empresa) references Educalife.empresa;
alter table if exists Educalife.unidade add constraint FKgkct3hfn4iq153btcc4fi2o4 foreign key (id_tipo_logradouro) references Educalife.tipo_logradouro;
alter table if exists Educalife.unidade_contatos add constraint FKqg2rq7vs1jg46kkxcskgd5vcu foreign key (unidade_id) references Educalife.unidade;
alter table if exists Educalife.usuario_permissao add constraint FKlb3vrs2j1di31uaweoq33bn7n foreign key (id_papel_usuario) references Educalife.papel_usuario;
alter table if exists Educalife.usuario_permissao add constraint FK5wc2vh351r26qbqt1tc52sh4m foreign key (usuario_id) references Educalife.usuario;